- id: swift-format
  name: swift-format
  entry: swift-format format --in-place --recursive --parallel
  language: swift
  types: [swift]
  require_serial: true
- id: swift-lint
  name: swift-lint
  entry: swift-format lint
  language: swift
  types: [swift]
  require_serial: true
- id: swift-lint-strict
  name: swift-lint-strict
  entry: swift-format lint --strict
  language: swift
  types: [swift]
  require_serial: true
